# Generated by Django 5.2.1 on 2025-05-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licen.legalentity', verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='license',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licen.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('journalist', 'Бухгалтер'), ('moderator', 'Пользователь'), ('admin', 'Администратор')], default='journalist', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
