# Generated by Django 5.2.1 on 2025-05-16 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0002_license_legal_entity_alter_license_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя компьютера')),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный MAC-адрес', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='MAC-адрес')),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 адрес')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='licen.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['address', 'name'],
                'unique_together': {('ipv4_address', 'address')},
            },
        ),
        migrations.CreateModel(
            name='CryptoPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'КриптоПро',
                'verbose_name_plural': 'КриптоПро',
            },
        ),
        migrations.CreateModel(
            name='ECP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦП',
            },
        ),
        migrations.CreateModel(
            name='FiscalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
                ('zn', models.CharField(max_length=100, unique=True, verbose_name='ЗН')),
                ('reg_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('fn', models.CharField(max_length=100, unique=True, verbose_name='ФН')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'ФН',
                'verbose_name_plural': 'ФН',
            },
        ),
        migrations.CreateModel(
            name='HonestSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Честный знак',
                'verbose_name_plural': 'Честные знаки',
            },
        ),
        migrations.CreateModel(
            name='LicenseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('license_type', models.CharField(max_length=100, verbose_name='Тип лицензии')),
                ('license_id', models.PositiveIntegerField(verbose_name='ID лицензии')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания')),
                ('notification_type', models.CharField(choices=[('expiring_soon', 'Скоро истекает'), ('expired', 'Истек срок')], max_length=20, verbose_name='Тип уведомления')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_notifications', to='licen.computer', verbose_name='Компьютер')),
                ('user_notified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Уведомленный пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о лицензии',
                'verbose_name_plural': 'Уведомления о лицензиях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('mcd_id', models.CharField(max_length=100, unique=True, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'МЧД',
                'verbose_name_plural': 'МЧД',
            },
        ),
        migrations.CreateModel(
            name='OFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('reg_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'ОФД',
                'verbose_name_plural': 'ОФД',
            },
        ),
        migrations.CreateModel(
            name='RemoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(choices=[('teamviewer', 'TeamViewer'), ('anydesk', 'AnyDesk'), ('rdp', 'Remote Desktop'), ('other', 'Другое')], default='teamviewer', max_length=100, verbose_name='Тип доступа')),
                ('access_id', models.CharField(max_length=100, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль удаленного доступа')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_accesses', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Удаленный доступ',
                'verbose_name_plural': 'Удаленные доступы',
                'ordering': ['computer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UTMRSAKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'УТМ RSA Ключ',
                'verbose_name_plural': 'УТМ RSA Ключи',
            },
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.AddIndex(
            model_name='licensenotification',
            index=models.Index(fields=['is_sent'], name='licen_licen_is_sent_b87bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='licensenotification',
            index=models.Index(fields=['expiration_date'], name='licen_licen_expirat_ddce18_idx'),
        ),
        migrations.AddIndex(
            model_name='licensenotification',
            index=models.Index(fields=['notification_type'], name='licen_licen_notific_601a4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteaccess',
            unique_together={('name', 'access_id', 'computer')},
        ),
    ]
