# Generated by Django 5.2.1 on 2025-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0004_licensenotification_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensenotification',
            name='notification_type',
            field=models.CharField(choices=[('expiring_soon_30', 'Скоро истекает (30 дней)'), ('expiring_soon_7', 'Скоро истекает (7 дней)'), ('expiring_soon_5', 'Скоро истекает (5 дней)'), ('expiring_soon_1', 'Скоро истекает (1 день)'), ('expired', 'Истек срок')], max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
