# Generated by Django 5.2.1 on 2025-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0005_alter_licensenotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenotification',
            name='days_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось дней'),
        ),
    ]
