# Generated by Django 5.2.1 on 2025-05-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0007_licensenotification_unique_notification_per_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensenotification',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licen.address'),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licen.computer'),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='days_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licen.legalentity'),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='license_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='license_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='notification_type',
            field=models.CharField(choices=[('expiring_soon_30', 'Скоро истекает (30 дней)'), ('expiring_soon_7', 'Скоро истекает (7 дней)'), ('expiring_soon_5', 'Скоро истекает (5 дней)'), ('expiring_soon_1', 'Скоро истекает (1 день)'), ('expired', 'Истёк срок')], default='expiring_soon_7', max_length=25),
        ),
        migrations.AlterField(
            model_name='licensenotification',
            name='user_notified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
