# Generated by Django 5.2.1 on 2025-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0008_alter_licensenotification_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('moderator', 'Пользователь'), ('journalist', 'Бухгалтер'), ('admin', 'Администратор')], default='moderator', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
