# Generated by Django 5.2.1 on 2025-06-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='licen.city', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
