# Generated by Django 5.2.1 on 2025-06-04 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0010_network_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='city',
        ),
        migrations.AddField(
            model_name='network',
            name='inn',
            field=models.CharField(default=1, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
