# Generated by Django 5.2.1 on 2025-06-04 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0011_remove_network_city_network_inn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'ordering': ['name'], 'verbose_name': 'Сеть', 'verbose_name_plural': 'Сети'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name'], 'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.RemoveIndex(
            model_name='legalentity',
            name='licen_legal_inn_fe5ead_idx',
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Путое поле'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование сети'),
        ),
        migrations.AlterField(
            model_name='network',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='licen.legalentity', verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название юридического лица'),
        ),
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together={('name', 'city')},
        ),
        migrations.AddIndex(
            model_name='network',
            index=models.Index(fields=['inn'], name='licen_netwo_inn_ef6471_idx'),
        ),
    ]
