# Generated by Django 5.2.1 on 2025-06-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0013_alter_address_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='inn',
        ),
    ]
