# Generated by Django 5.2.1 on 2025-06-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0014_remove_legalentity_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='USAIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Дата начала действия (с)')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия (по)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='licen.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'ЕГАИС',
                'verbose_name_plural': 'ЕГАИС',
            },
        ),
    ]
