# Generated by Django 5.2.1 on 2025-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0015_usais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usais',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ'),
        ),
    ]
