# Generated by Django 5.2.1 on 2025-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0016_alter_usais_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honestsign',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='usais',
            name='key',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
