# Generated by Django 5.2.1 on 2025-06-06 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0018_userprofile_department_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_password', models.CharField(help_text='Введите пароль или зашифрованное значение', max_length=255, verbose_name='Пароль от почты')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='licen.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['full_name'],
            },
        ),
    ]
