# Generated by Django 5.2.1 on 2025-06-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licen', '0019_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensenotification',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licen.network'),
        ),
    ]
